configs:
  # general optimization parameters:
  batch_size: 10000
  max_epochs: 4000
  learning_rate: .005
  min_delta: 0.00000008
  patience: 30
  single_epoch_test_run: False
  # data simulation parameters:
  simulate: True
  save: False
  missing_percentage: 0.6
  nitems: 110
  N: 10000
  iteration: 1
  # General model parameters:
  model: 'ivae'
  mirt_dim: 10
  hidden_layer_size: 40
  hidden_layer_size2: 20
  # parameters when model=='pvae':
  p_emb_dim: 12
  p_hidden_dim: 24
  p_latent_dim: 24
  p_hidden_layer_dim: 24
  # parameters when model=='iwae':
  n_iw_samples: 5
  # parameters when model=='cvae':
  hidden_layer_size3: 50
  # onlyy for main
  which_data: 'dylan'
